"""added updated_at column in password_rest and email_verification table

Revision ID: a3054e679a08
Revises: 5c9781e69475
Create Date: 2026-10-10 16:38:34.344225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3054e679a08'
down_revision: Union[str, Sequence[str], None] = '5c9781e69475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('password_resets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_resets', 'updated_at')
    op.drop_column('email_verifications', 'updated_at')
    # ### end Alembic commands ###
